import {
  Building2,
  Camera,
  Droplets,
  FileText,
  HardHat,
  Home,
  RefreshCw,
  Sprout,
  Users,
  Waves,
  Wrench,
} from "lucide-react";

export const GET_NOTICE = "Hawaiʻi General Excise Tax (GET) of 4.7120% is applied to all rates.";

const singleFamilyRates = [
  { label: "Up to 1,000 sq. ft.", price: "$450" },
  { label: "1,001–1,200 sq. ft.", price: "$500" },
  { label: "1,201–2,000 sq. ft.", price: "$550" },
  { label: "2,001–2,500 sq. ft.", price: "$650" },
  { label: "2,501–3,000 sq. ft.", price: "$825" },
  { label: "Over 3,000 sq. ft.", estimate: true },
];

const condoRates = [
  { label: "Up to 700 sq. ft.", price: "$350" },
  { label: "701–1,200 sq. ft.", price: "$400" },
  { label: "1,201–1,500 sq. ft.", price: "$500" },
  { label: "Over 1,500 sq. ft.", price: "$600" },
];

const maintenanceSingleFamilyRates = [
  { label: "Up to 1,000 sq. ft.", price: "$400" },
  { label: "1,001–1,200 sq. ft.", price: "$450" },
  { label: "1,201–2,000 sq. ft.", price: "$500" },
  { label: "2,001–2,500 sq. ft.", price: "$600" },
  { label: "2,501–3,000 sq. ft.", price: "$750" },
  { label: "Over 3,000 sq. ft.", estimate: true },
];

const maintenanceCondoRates = [
  { label: "Up to 700 sq. ft.", price: "$325" },
  { label: "701–1,200 sq. ft.", price: "$375" },
  { label: "1,201–1,500 sq. ft.", price: "$450" },
  { label: "Over 1,500 sq. ft.", price: "$550" },
];

const newConstructionSingleFamilyRates = [
  { label: "Up to 1,000 sq. ft.", price: "$500" },
  { label: "1,001–1,200 sq. ft.", price: "$550" },
  { label: "1,201–2,000 sq. ft.", price: "$625" },
  { label: "2,001–2,500 sq. ft.", price: "$725" },
  { label: "2,501–3,000 sq. ft.", price: "$925" },
  { label: "Over 3,000 sq. ft.", estimate: true },
];

const newConstructionCondoRates = [
  { label: "Up to 700 sq. ft.", price: "$400" },
  { label: "701–1,200 sq. ft.", price: "$450" },
  { label: "1,201–1,500 sq. ft.", price: "$550" },
  { label: "Over 1,500 sq. ft.", price: "$675" },
];

export const inspectionClassifications = [
  {
    key: "blue",
    title: "Blue — Serviceable",
    summary: "Operating as intended with no material deficiency observed.",
    description:
      "The system or component was operating as intended at the time of inspection, with no material deficiency observed. Normal aging, routine upkeep, and conditions consistent with the component’s type and service life may still be present. Continued monitoring and regular maintenance are recommended.",
  },
  {
    key: "green",
    title: "Green — Maintenance",
    summary: "Maintenance, manageable repair, DIY item, or recommended improvement.",
    description:
      "The observation relates to routine maintenance, a manageable repair, a potential do-it-yourself item, or a recommended upgrade. These conditions generally do not represent an immediate safety concern or significant functional failure; however, prolonged neglect may contribute to deterioration, reduced performance, or progression to a Yellow or Red condition.",
  },
  {
    key: "yellow",
    title: "Yellow — Repair / Evaluate",
    summary: "A material condition warrants timely repair, correction, or further evaluation.",
    description:
      "The system or component was not operating as intended, showed a material defect, or presented a condition warranting timely attention. If left unaddressed, the concern may contribute to property damage, reduced performance, or an unreasonable risk to people or property. Further evaluation by an appropriately qualified professional may be recommended.",
  },
  {
    key: "red",
    title: "Red — Significant / Prompt Action",
    summary: "A significant condition warrants prompt evaluation and corrective action.",
    description:
      "The observation identifies a significant defect, active or developing damage, substantial system or component failure, or a condition that may pose a meaningful risk to people or property. Prompt evaluation and corrective action by the appropriately qualified professional are recommended.",
  },
  {
    key: "gray",
    title: "Gray — Limitation / Referral",
    summary: "The area was limited or the condition requires specialist evaluation.",
    description:
      "A system, component, or area could not be fully inspected because it was inaccessible, concealed, obstructed, shut down, unsafe to operate, outside the agreed scope, or otherwise restricted. Gray may also identify an observation requiring evaluation by an appropriately qualified specialist. A limitation or referral does not, by itself, indicate that the component is defective.",
  },
];

export const inspectionServices = [
  {
    id: "full-residential",
    pageId: "inspection-full-residential",
    slug: "full-residential",
    path: "/services/home-inspections/full-residential",
    title: "Full Residential Home Inspection",
    shortTitle: "Full Residential",
    short: "A comprehensive visual, non-invasive review of readily accessible residential systems and components.",
    image: "/images/inspection-full-residential.jpg",
    icon: Home,
    bestFor: "Buyers, sellers and homeowners who want the broadest residential inspection scope.",
    startingPrice: "$450",
    seoTitle: "Full Residential Home Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Full residential home inspection on Hawaiʻi Island with defined scope, photographic reporting, clear classifications, limitations and practical follow-up guidance.",
    scope: [
      "Site conditions, grading, drainage, vegetation clearances, walking surfaces and readily visible site concerns",
      "Foundation and readily accessible structural components, including visible framing, supports, crawlspaces and attics",
      "Roof coverings, drainage components, flashings, penetrations and accessible roof-related conditions",
      "Exterior walls, cladding, windows, doors, lanais, decks, stairs, guards and readily visible weather-resistance conditions",
      "Plumbing supply, drainage, fixtures, water heating and accessible water-system components",
      "Closed-cover visual review of accessible electrical service equipment, branch-system components, receptacles, switches, lighting and normal user-level safety devices",
      "Cooling, ventilation, condensate management and accessible HVAC components",
      "Accessible propane or fuel-gas components and appliance interfaces when present",
      "Interior rooms, kitchen, bathrooms, laundry, garage and included built-in appliances",
      "Supplemental thermal imaging and moisture measurements when useful and appropriate, with photographic documentation of material findings and limitations",
    ],
    boundaries: [
      "Not a destructive inspection, repair service, or dismantling of equipment.",
      "Not an inspection that removes electrical panel dead fronts or equipment service covers.",
      "Not an engineering analysis, structural-capacity determination, or comprehensive code-compliance certification.",
      "Not a pest-species or infestation certification, mold assessment, environmental sampling service, or laboratory water-quality certification.",
      "Not a dedicated operational pool/spa or irrigation inspection unless that service is specifically added to the inspection agreement.",
    ],
    deliverable: "A client-friendly photographic report documenting observed conditions, material limitations, recommended support or referral actions, and ATS’s Blue / Green / Yellow / Red / Gray classification system.",
    pricing: [
      { title: "Single-Family Homes", rows: singleFamilyRates },
      { title: "Condominiums", rows: condoRates },
    ],
    pricingNotes: [
      "Total inspected square footage includes garages, lanais and other areas included in the agreed inspection scope. Square footage is subject to site verification.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family-home schedule.",
    ],
  },
  {
    id: "buyer",
    pageId: "inspection-buyers-home",
    slug: "buyers-home-inspection",
    path: "/services/home-inspections/buyers-home-inspection",
    title: "Buyer’s Home Inspection",
    shortTitle: "Buyer’s Inspection",
    short: "A comprehensive residential inspection organized specifically around a buyer’s due-diligence needs.",
    image: "/images/inspection-buyer.jpg",
    icon: Users,
    bestFor: "Prospective buyers during an inspection, due-diligence or contingency period.",
    startingPrice: "$350 condo / $450 home",
    seoTitle: "Buyer’s Home Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Buyer-focused home inspection on Hawaiʻi Island with visual, non-invasive system review, photographic findings, limitations and specialist follow-up guidance.",
    scope: [
      "The applicable Full Residential or Condo/Townhome physical inspection scope",
      "Material repair and evaluation concerns, maintenance considerations and safety-related observations",
      "Areas requiring specialist follow-up and components that were inaccessible or non-operational",
      "Documents or information that may warrant additional review",
      "Near-term ownership and maintenance planning, including buyer-reported concerns provided before or during the inspection",
    ],
    boundaries: [
      "Not an appraisal, property valuation, or repair-cost estimate.",
      "Not a negotiation strategy, legal opinion, or seller-disclosure interpretation.",
      "Not a recommendation about whether the client should purchase the property.",
      "Not an expansion beyond the visual, non-invasive scope boundaries of the applicable residential inspection.",
    ],
    deliverable: "A detailed inspection report plus buyer-focused organization of observations, limitations, recommended referrals and appropriate follow-up, without assigning repair costs or negotiating terms.",
    pricing: [
      { title: "Single-Family Homes", rows: singleFamilyRates },
      { title: "Condominiums", rows: condoRates },
    ],
    pricingNotes: [
      "Buyer inspections use the applicable Full Residential or Condo/Townhome rate based on property type and total inspected area.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family-home schedule.",
    ],
  },
  {
    id: "pre-listing",
    pageId: "inspection-pre-listing",
    slug: "pre-listing-home-inspection",
    path: "/services/home-inspections/pre-listing-home-inspection",
    title: "Pre-Listing Home Inspection",
    shortTitle: "Pre-Listing",
    short: "A comprehensive inspection performed before a property is marketed for sale.",
    image: "/images/inspection-pre-listing.jpg",
    icon: FileText,
    bestFor: "Owners who want to better understand visible property conditions before listing the home for sale.",
    startingPrice: "$350 condo / $450 home",
    seoTitle: "Pre-Listing Home Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Pre-listing home inspection on Hawaiʻi Island for owners who want documented visible conditions, maintenance needs and appropriate specialist follow-up before marketing.",
    scope: [
      "The applicable Full Residential or Condo/Townhome physical inspection scope",
      "Visible conditions that could warrant repair or further evaluation",
      "Deferred maintenance and specialist-referral needs",
      "Non-operational or inaccessible components and useful repair or service documentation",
      "Seller-oriented preparation planning without duplicating physical findings already documented in the technical sections",
    ],
    boundaries: [
      "Not legal or seller-disclosure advice.",
      "Not an appraisal, property valuation, pricing strategy, or marketability opinion.",
      "Not a prediction of buyer reactions or a negotiation recommendation.",
      "Not an expansion beyond the visual, non-invasive scope boundaries of the applicable residential inspection.",
    ],
    deliverable: "A seller-focused condition report that helps the owner organize observed conditions, maintenance, repairs, documentation and specialist follow-up before marketing the property.",
    pricing: [
      { title: "Single-Family Homes", rows: singleFamilyRates },
      { title: "Condominiums", rows: condoRates },
    ],
    pricingNotes: [
      "Pre-listing inspections use the applicable Full Residential or Condo/Townhome rate based on property type and total inspected area.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family-home schedule.",
    ],
  },
  {
    id: "maintenance",
    pageId: "inspection-home-maintenance",
    slug: "home-maintenance-inspection",
    path: "/services/home-inspections/home-maintenance-inspection",
    title: "Home Maintenance Inspection",
    shortTitle: "Home Maintenance",
    short: "A comprehensive condition review designed around preventive maintenance and long-term property care.",
    image: "/images/inspection-maintenance.jpg",
    icon: Wrench,
    bestFor: "Current homeowners, second-home owners and clients establishing or updating a long-term maintenance plan.",
    startingPrice: "$325 condo / $400 home",
    seoTitle: "Home Maintenance Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Home maintenance inspection on Hawaiʻi Island focused on visible deterioration, deferred maintenance, moisture management, corrosion and practical property-care planning.",
    scope: [
      "Visible deterioration, deferred maintenance and developing conditions",
      "Water-management, drainage, exterior coating, sealant and weather-exposure conditions",
      "Corrosion, salt-related deterioration, ventilation and moisture-management concerns",
      "Accessible structural, building-envelope, plumbing, electrical, cooling and other installed-system observations",
      "Components that should be serviced, repaired, monitored or further evaluated",
      "Baseline photography where useful for future comparison and practical recurring or near-term maintenance planning",
    ],
    boundaries: [
      "Not a guarantee of remaining service life or future performance.",
      "Not a repair or maintenance service; corrective work is not performed as part of the inspection.",
      "Not an ongoing property-management, caretaking, or maintenance service.",
      "Not a substitute for appropriately licensed repair or specialist services when those services are required.",
    ],
    deliverable: "A maintenance-oriented photographic report organized by classification, recommended timing and practical next actions so the owner can build a property-care plan.",
    pricing: [
      { title: "Single-Family Home Maintenance", rows: maintenanceSingleFamilyRates },
      { title: "Condominium Maintenance", rows: maintenanceCondoRates },
    ],
    pricingNotes: [
      "Total inspected square footage includes garages, lanais and other areas included in the agreed inspection scope. Square footage is subject to site verification.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family maintenance schedule.",
    ],
  },
  {
    id: "condo-townhome",
    pageId: "inspection-condo-townhome",
    slug: "condo-townhome-inspection",
    path: "/services/home-inspections/condo-townhome-inspection",
    title: "Condo and Townhome Inspection",
    shortTitle: "Condo & Townhome",
    short: "A residential inspection tailored to the unit, included exclusive-use areas and visible interfaces with shared systems.",
    image: "/images/inspection-condo-townhome.jpg",
    icon: Building2,
    bestFor: "Condominium and townhome buyers, sellers and owners.",
    startingPrice: "$350",
    seoTitle: "Condo & Townhome Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Condo and townhome inspection on Hawaiʻi Island focused on the unit, included exclusive-use areas and visible interfaces with association-controlled systems.",
    scope: [
      "Interior ceilings, walls, floors, doors and windows within the inspected unit",
      "Unit plumbing fixtures and accessible supply and drainage components",
      "Unit electrical components using closed-cover and normal user-level inspection methods",
      "Cooling and ventilation equipment serving the unit",
      "Kitchen, bathrooms, laundry areas and included built-in appliances",
      "Included lanais, balconies, garages, storage areas and other exclusive-use spaces",
      "Visible building-envelope conditions affecting the unit and readily visible interfaces with shared or association-controlled systems",
    ],
    boundaries: [
      "Not a broad inspection of site conditions, foundations, roofs, building-wide systems, or association-controlled common elements unless specifically included, readily accessible, and within the agreed scope.",
      "Not an interpretation of condominium declarations, bylaws, or legal maintenance responsibility between the owner and association.",
      "Not a representation that concealed or inaccessible shared systems were inspected.",
    ],
    deliverable: "A unit-focused photographic report distinguishing inspected components from visible conditions that may require association documents, management confirmation or specialist evaluation.",
    pricing: [{ title: "Condominiums", rows: condoRates }],
    pricingNotes: [
      "Total inspected square footage includes garages, lanais and other areas included in the agreed inspection scope. Square footage is subject to site verification.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family-home schedule.",
    ],
  },
  {
    id: "new-construction",
    pageId: "inspection-new-construction",
    slug: "new-construction-home-inspection",
    path: "/services/home-inspections/new-construction-home-inspection",
    title: "New Construction Home Inspection",
    shortTitle: "New Construction",
    short: "An independent visual review of installed and readily accessible conditions before final acceptance or a builder-warranty milestone.",
    image: "/images/inspection-new-construction.jpg",
    icon: HardHat,
    bestFor: "New-construction buyers, owners approaching final acceptance, and homeowners approaching a builder-warranty milestone.",
    startingPrice: "$400 condo / $500 home",
    seoTitle: "New Construction Home Inspection | Hawaiʻi Island | ATS",
    seoDescription: "New construction home inspection on Hawaiʻi Island documenting visible completion, installation and operational concerns before acceptance or warranty milestones.",
    scope: [
      "Applicable installed and readily accessible systems and components included in a residential inspection",
      "Visible completion, workmanship, finish and installation concerns",
      "Incomplete or damaged finishes and accessible installed-system operation using normal user controls",
      "Doors, windows, cabinets, fixtures, site and drainage conditions where accessible",
      "Visible roof, exterior, attic, interior, plumbing, electrical and mechanical conditions",
      "Completion-readiness observations, photographic punch-list documentation and owner-reported warranty concerns when applicable",
    ],
    boundaries: [
      "Not a municipal building inspection or code-compliance certification.",
      "Not an architectural or engineering service, plan/specification-compliance review, or concealed-work verification.",
      "Not a certification of contractor workmanship or a replacement for the builder’s quality-control and warranty obligations.",
    ],
    deliverable: "A photographic report of visible installed conditions, incomplete or concerning items, limitations and appropriate referrals for discussion with the builder or qualified professional.",
    pricing: [
      { title: "Single-Family New Construction", rows: newConstructionSingleFamilyRates },
      { title: "New Construction Condominiums", rows: newConstructionCondoRates },
    ],
    pricingNotes: [
      "Pricing applies to final/pre-acceptance or warranty-stage visual inspections of installed, readily accessible conditions.",
      "Townhomes and condominium units with air-conditioning systems are priced using the applicable single-family new-construction schedule.",
    ],
  },
  {
    id: "reinspection",
    pageId: "inspection-repair-verification",
    slug: "repair-verification-reinspection",
    path: "/services/home-inspections/repair-verification-reinspection",
    title: "Repair Verification and Reinspection",
    shortTitle: "Repair Verification",
    short: "A focused return inspection of specifically identified repairs or previously reported conditions.",
    image: "/images/inspection-reinspection.jpg",
    icon: RefreshCw,
    bestFor: "Clients seeking documented follow-up after specified repairs or specialist work.",
    startingPrice: "$175",
    seoTitle: "Repair Verification & Reinspection | Hawaiʻi Island | ATS",
    seoDescription: "Focused repair verification and reinspection on Hawaiʻi Island documenting the visible status of agreed repair items and remaining limitations.",
    scope: [
      "Review of the original finding or specifically agreed repair item",
      "Visual inspection of the accessible repaired area and comparison with prior photographs or report information",
      "Normal user-level operation where appropriate, included and safe",
      "Photographic documentation of the current condition",
      "Identification of items that appear addressed, partially addressed, unchanged, inaccessible or not verifiable",
      "Referral back to the repairing professional when certification or additional diagnosis is appropriate",
    ],
    boundaries: [
      "Not a new whole-home inspection unless separately contracted.",
      "Not a certification of concealed work, contractor workmanship, code compliance, permit closeout, or future durability.",
      "Not an evaluation of unrelated systems unless those systems are specifically added to the written agreement.",
    ],
    deliverable: "A focused photographic reinspection report describing the visible status of the agreed items at the return visit and any limitations or recommended follow-up.",
    pricing: [{
      title: "Repair Verification / Reinspection",
      rows: [
        { label: "1–5 items", price: "$175" },
        { label: "6–10 items", price: "$225" },
        { label: "11–20 items", price: "$300" },
        { label: "More than 20 items or complex reinspection", estimate: true },
      ],
    }],
    pricingNotes: ["Pricing may be adjusted when extensive third-party documentation, multiple inaccessible locations or unusually complex systems require additional review."],
  },
  {
    id: "moisture",
    pageId: "inspection-moisture-water-intrusion",
    slug: "moisture-water-intrusion-inspection",
    path: "/services/home-inspections/moisture-water-intrusion-inspection",
    title: "Moisture and Water-Intrusion Inspection",
    shortTitle: "Moisture & Water Intrusion",
    short: "A targeted, non-destructive investigation of reported or suspected moisture intrusion.",
    image: "/images/inspection-moisture-detail.jpg",
    icon: Droplets,
    bestFor: "Leaks, staining, musty conditions, post-storm concerns, previous water events or unexplained moisture indicators.",
    startingPrice: "$250",
    badge: "Add-on option",
    seoTitle: "Moisture & Water-Intrusion Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Targeted moisture and water-intrusion inspection on Hawaiʻi Island using visual observations, moisture readings and supplemental thermal imaging when appropriate.",
    scope: [
      "Review of reported conditions and available history",
      "Visual inspection of the affected area and related building components",
      "Moisture-meter measurements at representative and comparison locations",
      "Thermal imaging under conditions where it may provide useful supplemental information",
      "Moisture-pattern mapping and review of readily visible roof, exterior, plumbing, drainage, condensate or other possible source pathways",
      "Correlation of observations between adjacent surfaces or spaces, with photographs of visible conditions and material instrument readings",
    ],
    boundaries: [
      "Not a method for seeing through walls or independently establishing moisture presence; thermal imaging is a supplemental screening tool.",
      "Not a certification of concealed conditions; moisture readings are screening and documentation tools.",
      "Not a mold-species identification, indoor-air-quality certification, environmental sampling, or destructive leak-testing service.",
      "Not a guarantee of the exact concealed source or full extent of damage.",
    ],
    deliverable: "A targeted photographic report documenting observed anomalies, readings, source-correlation observations, limitations and recommended specialist follow-up.",
    pricing: [{
      title: "Moisture / Water-Intrusion",
      rows: [
        { label: "Localized investigation — one primary concern/area", price: "$250" },
        { label: "Multi-area investigation — several related areas", price: "$350" },
        { label: "Complex or whole-property source-correlation investigation", price: "Starting at $450" },
        { label: "Targeted add-on during a qualifying residential inspection", price: "Starting at $150" },
      ],
    }],
  },
  {
    id: "irrigation",
    pageId: "inspection-irrigation-system",
    slug: "irrigation-system-inspection",
    path: "/services/home-inspections/irrigation-system-inspection",
    title: "Irrigation System Inspection",
    shortTitle: "Irrigation System",
    short: "A user-level operational review of accessible landscape-irrigation components and visible effects on the property.",
    image: "/images/inspection-irrigation.jpg",
    icon: Sprout,
    bestFor: "Properties with irrigation systems, high water use, dry zones, overspray, visible leakage, aging components or irrigation-related drainage concerns.",
    startingPrice: "$200",
    badge: "Add-on option",
    seoTitle: "Irrigation System Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Irrigation system inspection on Hawaiʻi Island covering accessible controls, representative zones, visible leaks, runoff, overspray and property impacts.",
    scope: [
      "Accessible controller and normal operating settings",
      "Visible source and shutoff context",
      "Operation of accessible irrigation zones when safe and practical",
      "Sprinkler heads, drip emitters, accessible valves, filters and other visible components",
      "Visible leakage, damaged components, obvious coverage deficiencies and overspray",
      "Runoff, ponding, erosion and irrigation-related water contact with the building",
      "Photographic documentation of reportable conditions",
    ],
    boundaries: [
      "Not a backflow-prevention certification.",
      "Not a buried-pipe or valve-locating service, pressure test, or design-flow calculation.",
      "Not a water-quality certification or landscape-design adequacy evaluation.",
      "Not an irrigation repair or adjustment service.",
    ],
    deliverable: "An irrigation condition report documenting representative operation, visible component conditions, property impacts, limitations and recommended follow-up.",
    pricing: [{
      title: "Irrigation Systems",
      rows: [
        { label: "Up to 6 zones", price: "$200" },
        { label: "7–12 zones", price: "$275" },
        { label: "13–18 zones", price: "$350" },
        { label: "More than 18 zones, large acreage or complex systems", estimate: true },
        { label: "Add-on to a qualifying residential inspection — up to 6 zones", price: "Starting at $150" },
      ],
    }],
  },
  {
    id: "pool-spa",
    pageId: "inspection-pool-spa-equipment",
    slug: "pool-spa-equipment-inspection",
    path: "/services/home-inspections/pool-spa-equipment-inspection",
    title: "Pool/Spa and Equipment Inspection",
    shortTitle: "Pool / Spa",
    short: "A visual and user-level operational inspection of readily accessible pool or spa components, equipment and safety-related conditions.",
    image: "/images/inspection-pool-spa.jpg",
    icon: Waves,
    bestFor: "Properties with a swimming pool, spa or combined pool/spa system.",
    startingPrice: "$50 spa / $150 pool",
    badge: "Add-on option",
    seoTitle: "Pool & Spa Equipment Inspection | Hawaiʻi Island | ATS",
    seoDescription: "Pool and spa equipment inspection on Hawaiʻi Island covering visible safety features, deck/surfaces, accessible equipment and normal user-level operation.",
    scope: [
      "Readily visible pool/spa barriers, gates and safety-related conditions",
      "Deck, coping, surrounding walking surfaces and visible drainage conditions",
      "Accessible shell, finish, waterline and visible surface conditions",
      "Pumps, filters, accessible circulation equipment and visible piping under normal user-level operation",
      "Heater and treatment-system controls using normal user interfaces when appropriate",
      "Visible electrical and bonding interfaces without opening electrical or service equipment",
      "Accessible spa-specific components, visible leakage, corrosion, deterioration and equipment-area conditions",
      "Thermal imaging when it provides useful supplemental information, with photographic documentation of reportable conditions",
    ],
    boundaries: [
      "Not an electrical-panel/service-cover inspection or equipotential-bonding certification.",
      "Not a gas-pressure, combustion, or leak certification.",
      "Not a structural-engineering evaluation, water-chemistry certification, suction/entrapment certification, or pressure-testing service.",
      "Not a concealed leak-location service or comprehensive code-compliance certification.",
    ],
    deliverable: "A pool/spa condition report with photographs, visible safety and equipment observations, limitations, classifications and recommended specialist follow-up.",
    pricing: [{
      title: "Pool & Spa",
      rows: [
        { label: "Pool & Spa", price: "$200" },
        { label: "Pool Only", price: "$150" },
        { label: "Spa Only", price: "$50" },
      ],
    }],
    pricingNotes: ["Unusually complex equipment systems, multiple pools/spas, extensive water features or commercial-style equipment may require a custom quote."],
  },
  {
    id: "arrival-departure",
    pageId: "inspection-arrival-departure",
    slug: "custom-arrival-departure-inspections",
    path: "/services/home-inspections/custom-arrival-departure-inspections",
    title: "Custom Arrival and Departure Inspections",
    shortTitle: "Arrival / Departure",
    short: "A customized photographic condition inspection created around the owner’s approved checklist.",
    image: "/images/inspection-arrival-departure.jpg",
    icon: Camera,
    bestFor: "Second homes, periodically occupied residences and owner-managed vacation-rental properties requiring consistent condition documentation.",
    startingPrice: "Custom quote",
    seoTitle: "Arrival & Departure Condition Inspections | Hawaiʻi Island | ATS",
    seoDescription: "Custom arrival and departure condition inspections on Hawaiʻi Island with owner-approved checklists, photographic documentation and defined user-level checks.",
    scope: [
      "Arrival or departure access condition and exterior condition views",
      "Room-by-room photographic documentation",
      "Owner-designated furnishings, inventory, appliances and equipment",
      "Normal user-level operation of specifically authorized items",
      "Pool/spa or other amenity condition documentation when included in the written checklist",
      "Owner-authorized utility or control settings",
      "Visible damage, missing items, unexpected conditions and prompt notification of material visible concerns",
      "Safety and closeout observations defined in the agreed checklist",
    ],
    boundaries: [
      "Not a comprehensive technical home inspection; this is a condition-documentation service.",
      "Not property management, leasing, guest or tenant administration, rent handling, or housekeeping certification.",
      "Not a determination of responsibility for damage or a tenancy, rental, or owner-management decision.",
    ],
    deliverable: "A dated photographic condition record tailored to the owner-approved checklist, documenting the agreed areas, items, visible conditions and exceptions.",
    pricingCustom: true,
    pricingFactors: [
      "Total inspected square footage",
      "Number of rooms, separate areas and accessory spaces",
      "Quantity of furnishings or inventory requiring documentation",
      "Number of appliances or equipment items requiring user-level checks",
      "Pool, spa and other amenities",
      "Exterior areas and accessory structures",
      "Required number and detail of photographs",
      "Checklist complexity, reporting requirements and requested inspection frequency",
    ],
  },
];

export const INSPECTION_PAGE_PATHS = Object.fromEntries(
  inspectionServices.map((inspection) => [inspection.pageId, inspection.path])
);

export const INSPECTION_PAGE_SEO = Object.fromEntries(
  inspectionServices.map((inspection) => [
    inspection.pageId,
    {
      title: inspection.seoTitle,
      description: inspection.seoDescription,
      image: inspection.image,
    },
  ])
);

export function getInspectionByPageId(pageId) {
  return inspectionServices.find((inspection) => inspection.pageId === pageId);
}

export function getInspectionById(id) {
  return inspectionServices.find((inspection) => inspection.id === id);
}
